-- src/main/resources/db/migration/V11__Create_Dispatch_Details_Table.sql

-- Create the necessary table for storing dispatch details if it doesn't exist.
CREATE TABLE IF NOT EXISTS dispatch_details (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_number VARCHAR2(50) NOT NULL,
    airway_bill_number VARCHAR2(50),
    delivery_type VARCHAR2(50),
    vendor_information VARCHAR2(100),
    consignee_name VARCHAR2(100),
    con_add1 VARCHAR2(100),
    con_add2 VARCHAR2(100),
    con_add3 VARCHAR2(100),
    con_city VARCHAR2(50),
    con_state VARCHAR2(50),
    des_pin VARCHAR2(20),
    pick_request_number VARCHAR2(50),
    reference_number VARCHAR2(50),
    weight NUMBER,
    weight_unit VARCHAR2(10),
    destination_type VARCHAR2(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Ensure the table is created with the necessary columns for storing dispatch details.