CREATE TABLE NOMINEE_INFO (
  CONTRACT_ID VARCHAR2(50) NOT NULL,
  VERSION_NO NUMBER NOT NULL,
  USER_ID VARCHAR2(50),
  SCAN_DATE DATE,
  FLAGS VARCHAR2(10),
  DESCRIPTION VARCHAR2(255),
  PRIMARY KEY (CONTRACT_ID, VERSION_NO)
);