CREATE TABLE underwriting_comments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR2(50) NOT NULL,
    comment_date TIMESTAMP NOT NULL,
    comments CLOB NOT NULL,
    policy_no VARCHAR2(50) NOT NULL
);

CREATE INDEX idx_underwriting_comments_policy_no ON underwriting_comments (policy_no);