-- Purpose: Create the necessary table for storing user authentication data if it doesn't exist.

CREATE TABLE IF NOT EXISTS user_authentication (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supervisor_id VARCHAR2(10) NOT NULL,
    password VARCHAR2(10) NOT NULL,
    comments VARCHAR2(500),
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Ensure supervisor_id is always stored in uppercase
CREATE OR REPLACE TRIGGER trg_uppercase_supervisor_id
BEFORE INSERT OR UPDATE ON user_authentication
FOR EACH ROW
BEGIN
    :NEW.supervisor_id := UPPER(:NEW.supervisor_id);
END;
/